# Generated by Django 3.1.6 on 2021-02-04 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('date_sub', models.DateTimeField(auto_now_add=True, verbose_name='date_sub')),
            ],
        ),
    ]
