# Generated by Django 3.1.6 on 2021-02-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
